"""remove test field

Revision ID: 1d2510a5b8a1
Revises: fa8b5679c85c
Create Date: 2023-11-13 17:53:23.205463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2510a5b8a1'
down_revision = 'fa8b5679c85c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
