"""initial migration

Revision ID: 234a959ba933
Revises: 
Create Date: 2023-11-13 17:33:52.709710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234a959ba933'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###
