"""add date field

Revision ID: 36d7046ade22
Revises: 1d2510a5b8a1
Create Date: 2023-11-14 16:08:08.928639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36d7046ade22'
down_revision = '1d2510a5b8a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lts', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
